# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-MLNetWl_uttyWpmGciEmh2H54__v-Qm
"""

#Importing Directories
import numpy as np
import pandas as pd

df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn (1).csv')

"""**DATA CLEANING**

"""

# ==========================================
# DATA CLEANING
# ==========================================

# 1. Check missing values
print("Missing Values:")
print(df.isnull().sum())

# ==========================================

# 2. Check duplicate rows
print("\nDuplicate Rows:")
print(df.duplicated().sum())

# ==========================================

# 3. Remove customerID column
# It is just an identifier and doesn't help prediction

df.drop("customerID", axis=1, inplace=True)

# ==========================================

# 4. Check data types

print("\nData Types:")
print(df.dtypes)

# ==========================================

# 5. Convert TotalCharges to numeric
# Some rows contain blank spaces

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

# ==========================================

# 6. Check missing values again

print("\nMissing Values After Conversion:")
print(df.isnull().sum())

# ==========================================

# 7. Fill missing values in TotalCharges
# Using median because it is robust to outliers

df["TotalCharges"] = df["TotalCharges"].fillna(
    df["TotalCharges"].median()
)

# ==========================================

# 8. Verify everything is clean

print("\nFinal Missing Values:")
print(df.isnull().sum())

print("\nFinal Shape:")
print(df.shape)

print("\nUpdated Info:")
print(df.info())

"""WE DROPPED CUSTOMER ID COLUMN AND CONVERTED THE DATA TYPE OF TOTAL CHARGES FRM OBJECT TO FLOAT64 AND CHECKED AND PREPARED A DATASET FOR OUR ML MODEL.

**EDA(EXPLORATORY DATA ANALYSIS)**
"""

import matplotlib.pyplot as plt
import seaborn as sns

#Check Churn Distribution
print(df["Churn"].value_counts())

sns.countplot(x="Churn", data=df)

plt.title("Customer Churn Distribution")
plt.show()

plt.figure(figsize=(8,5))

sns.countplot(
    x="Contract",
    hue="Churn",
    data=df
)

plt.title("Churn by Contract Type")
plt.show()

#Churn vs gender
plt.figure(figsize=(6,4))

sns.countplot(
    x="gender",
    hue="Churn",
    data=df
)

plt.title("Churn by Gender")
plt.show()

#Churn vs Internet service
plt.figure(figsize=(8,5))

sns.countplot(
    x="InternetService",
    hue="Churn",
    data=df
)

plt.title("Churn by Internet Service")
plt.show()

#Monthly charges distribution
plt.figure(figsize=(8,5))

sns.histplot(
    df["MonthlyCharges"],
    bins=30,
    kde=True
)

plt.title("Monthly Charges Distribution")
plt.show()

#Tenure dist
plt.figure(figsize=(8,5))

sns.histplot(
    df["tenure"],
    bins=30,
    kde=True
)

plt.title("Customer Tenure Distribution")
plt.show()

plt.figure(figsize=(8,5))

sns.boxplot(
    x="Churn",
    y="tenure",
    data=df
)

plt.title("Tenure vs Churn")
plt.show()

"""EDA HELPED US IN IDENTIFYING THE DATASET MORE BETTER AND THE MEANINGFUL PATTERNS

**FEATURE ENGINEEERING**
"""

# ==========================================
# FEATURE ENGINEERING & PREPROCESSING
# ==========================================

# Create a copy (good practice)
df_model = df.copy()

# ==========================================
# FIX CHURN COLUMN
# ==========================================

# Remove extra spaces
df_model["Churn"] = df_model["Churn"].astype(str).str.strip()

# Convert target variable to numeric
df_model["Churn"] = df_model["Churn"].map({
    "Yes": 1,
    "No": 0
})

# Check for missing values in target
print("Missing values in Churn:")
print(df_model["Churn"].isnull().sum())

# ==========================================
# SEPARATE FEATURES AND TARGET
# ==========================================

X = df_model.drop("Churn", axis=1)
y = df_model["Churn"]

# ==========================================
# IDENTIFY CATEGORICAL COLUMNS
# ==========================================

categorical_cols = X.select_dtypes(include="object").columns

print("\nCategorical Columns:")
print(categorical_cols)

# ==========================================
# ONE-HOT ENCODING
# ==========================================

X = pd.get_dummies(
    X,
    columns=categorical_cols,
    drop_first=True
)

# ==========================================
# FINAL CHECKS
# ==========================================

print("\nShape of X:")
print(X.shape)

print("\nShape of y:")
print(y.shape)

print("\nMissing values in X:")
print(X.isnull().sum().sum())

print("\nMissing values in y:")
print(y.isnull().sum())

print("\nData Types:")
print(X.dtypes.value_counts())

# ==========================================
# REMOVE ANY REMAINING NaN ROWS
# (Safety Check)
# ==========================================

combined = pd.concat([X, y], axis=1)

combined.dropna(inplace=True)

X = combined.drop("Churn", axis=1)
y = combined["Churn"]

print("\nFinal Shape After NaN Removal:")
print(X.shape)
print(y.shape)

print("\nDataset Ready For Machine Learning ✅")

print(X.shape)
print(y.shape)

print(X.isnull().sum().sum())
print(y.isnull().sum())

"""**SPLITTING OUR DATA**"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Set Shape:", X_train.shape)
print("Testing Set Shape:", X_test.shape)

#RANDOM FOREST TRAINING
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)

# Probability Predictions
y_prob = rf.predict_proba(X_test)[:, 1]

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("\n========== MODEL PERFORMANCE ==========\n")

print("Accuracy :", round(accuracy_score(y_test, y_pred), 4))
print("Precision:", round(precision_score(y_test, y_pred), 4))
print("Recall   :", round(recall_score(y_test, y_pred), 4))
print("F1 Score :", round(f1_score(y_test, y_pred), 4))

# ==========================================
# CLASSIFICATION REPORT
# ==========================================

print("\n========== CLASSIFICATION REPORT ==========\n")
print(classification_report(y_test, y_pred))

# ==========================================
# CONFUSION MATRIX
# ==========================================

import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Random Forest Confusion Matrix")

plt.show()

# ==========================================
# FEATURE IMPORTANCE
# ==========================================

feature_importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n========== TOP 10 IMPORTANT FEATURES ==========\n")
print(feature_importance.head(10))

"""MODEL SAVING"""

# ==========================================
# SAVE RANDOM FOREST MODEL
# ==========================================

import pickle

with open("customer_churn_model.pkl", "wb") as file:
    pickle.dump(rf, file)

print("Model Saved Successfully!")

# ==========================================
# LOAD MODEL
# ==========================================

import pickle

with open("customer_churn_model.pkl", "rb") as file:
    loaded_model = pickle.load(file)

print("Model Loaded Successfully!")

with open("feature_columns.pkl", "wb") as file:
    pickle.dump(X.columns.tolist(), file)

print("Feature Names Saved!")

